# Generated by Django 6.0.3 on 2026-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_jobdescription_alter_resume_score_resume_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
