# Generated by Django 6.0.3 on 2026-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_resume_extracted_skills_resume_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='extracted_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job',
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
