# Generated by Django 6.0.3 on 2026-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_remove_resume_extracted_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='matched_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='problem',
            field=models.TextField(blank=True, default=''),
        ),
    ]
